'use client';
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import workerUrl from '../../lib/sim/lap.worker.ts?worker&url';
import {SF26_DEFAULT,SF26_PARAMETERS,SF26_MODEL_VERSION,validateSF26Setup,type SF26Setup} from '@/lib/sim/sf26Model';
import {CENTERLINE,type Trajectory} from '@/lib/sim/trajectory';
import {snapshot,stationSample,type Experiment} from '@/lib/sim/experiments';
import {sampleLap,type Lap} from '@/lib/sim/physics';
import {clockTime,changeClock,type PlaybackClock} from '@/lib/sim/motion';
import {Telemetry,formatTime} from './Telemetry';
import Experiments from './Experiments';
import SectionComparison from './SectionComparison';
import TrajectoryControls from './TrajectoryControls';
const Viewport=dynamic(()=>import('./Viewport'),{ssr:false});
// Keep the last session across garage/vehicle navigation without overwriting saved history.
let session:{setup:SF26Setup;reference:SF26Setup;name:string;trajectory:Trajectory;baselineMode:string;lap:Lap|null;baseline:Lap|null;completed:Experiment|null;resultA:Experiment|null;resultB:Experiment|null}|null=null;
export default function SF26Simulation(){
 const [setup,setSetup]=useState<SF26Setup>(session?.setup??{...SF26_DEFAULT}),[reference,setReference]=useState<SF26Setup>(session?.reference??{...SF26_DEFAULT}),[name,setName]=useState(session?.name??'SF-26 experiment'),[trajectory,setTrajectory]=useState<Trajectory>(session?.trajectory??CENTERLINE),[baselineMode,setBaselineMode]=useState(session?.baselineMode??'same');
 const [lap,setLap]=useState<Lap|null>(session?.lap??null),[baseline,setBaseline]=useState<Lap|null>(session?.baseline??null),[completed,setCompleted]=useState<Experiment|null>(session?.completed??null),[resultA,setResultA]=useState<Experiment|null>(session?.resultA??null),[resultB,setResultB]=useState<Experiment|null>(session?.resultB??null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[rate,setRate]=useState(1),[saved,setSaved]=useState<{name:string;setup:SF26Setup}[]>([]);
 const worker=useRef<Worker|null>(null),request=useRef(0),timeout=useRef<ReturnType<typeof setTimeout>|null>(null),labels=useRef({name:'',line:'',baselineLine:''}),file=useRef<HTMLInputElement>(null);
 const clock=useRef<PlaybackClock>({time:0,wall:0,rate:1,playing:false,duration:session?.lap?.lapTime??0});
 useEffect(()=>{session={setup,reference,name,trajectory,baselineMode,lap,baseline,completed,resultA,resultB};},[setup,reference,name,trajectory,baselineMode,lap,baseline,completed,resultA,resultB]);
 const getTime=()=>clockTime(clock.current,performance.now());
 const seek=(t:number)=>{changeClock(clock.current,performance.now(),{time:t});setTime(t);};
 const stop=()=>{changeClock(clock.current,performance.now(),{playing:false});setPlaying(false);};
 useEffect(()=>{try{const rows=JSON.parse(localStorage.getItem('apex-sf26-setups-v1')||'[]');if(!Array.isArray(rows)||rows.length>20)throw Error('Invalid saved SF-26 configurations.');setSaved(rows.map(r=>{if(r.vehicleId!=='sf26'||r.modelVersion!==SF26_MODEL_VERSION||typeof r.name!=='string')throw Error('Saved SF-26 setup version is incompatible.');return {name:r.name,setup:validateSF26Setup(r.setup)};}));}catch(e){setMessage(String(e));}
  const w=new Worker(workerUrl,{type:'module'});worker.current=w;
  w.onmessage=e=>{if(e.data.id!==request.current)return;if(timeout.current)clearTimeout(timeout.current);setBusy(false);if(e.data.error){setMessage(e.data.error);return;}const l=e.data.lap as Lap,a=e.data.baseline as Lap,b=snapshot(l,labels.current.name,labels.current.line),ar=snapshot(a,'SF-26 baseline',labels.current.baselineLine);setLap(l);setBaseline(a);setCompleted(b);setResultA(ar);setResultB(b);changeClock(clock.current,performance.now(),{time:0,duration:l.lapTime,playing:false});setTime(0);setPlaying(false);setMessage('Completed — immutable results saved separately from the editable setup.');};
  w.onerror=()=>{if(timeout.current)clearTimeout(timeout.current);setBusy(false);setMessage('Simulation worker failed. Reload to retry.');};
  return()=>{w.terminate();worker.current=null;if(timeout.current)clearTimeout(timeout.current);};
 },[]);
 useEffect(()=>{let id=0,last=0;const tick=()=>{const t=getTime();if(performance.now()-last>60){setTime(t);last=performance.now();}if(t>=clock.current.duration&&clock.current.playing){clock.current.playing=false;setPlaying(false);}id=requestAnimationFrame(tick);};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id);},[]);
 const run=()=>{try{const s=validateSF26Setup(setup),a=validateSF26Setup(reference);if(!worker.current)throw Error('Worker unavailable.');stop();setBusy(true);setMessage('Simulating SF-26…');labels.current={name,line:trajectory.name,baselineLine:baselineMode==='same'?trajectory.name:CENTERLINE.name};worker.current.postMessage({id:++request.current,vehicleId:'sf26',setup:s,baselineSetup:a,trajectory,baselineMode,baselineTrajectory:CENTERLINE});timeout.current=setTimeout(()=>{++request.current;setBusy(false);setMessage('Simulation timed out. Reload before retrying.');},60000);}catch(e){setMessage(String(e));}};
 const open=(a:Experiment,b:Experiment)=>{if(a.vehicleId!=='sf26'||b.vehicleId!=='sf26'){setMessage('Choose two SF-26 runs.');return;}stop();setBaseline(a.lap);setLap(b.lap);setResultA(a);setResultB(b);changeClock(clock.current,performance.now(),{time:0,duration:b.lap.lapTime});setTime(0);setMessage(a.modelVersion!==b.modelVersion?'Different model versions: potentially noncomparable.':'Saved results opened without rerunning.');};
 const saveSetup=()=>{try{const s=validateSF26Setup(setup);if(saved.length>=20)throw Error('20-configuration limit reached; export this setup. Existing setups were preserved.');const next=[...saved,{name:name.trim().slice(0,60)||'SF-26 setup',setup:s}];localStorage.setItem('apex-sf26-setups-v1',JSON.stringify(next.map(r=>({...r,vehicleId:'sf26',modelVersion:SF26_MODEL_VERSION,version:1}))));setSaved(next);setMessage('SF-26 configuration saved.');}catch(e){setMessage(String(e));}};
 const exportSetup=()=>{try{const data={vehicleId:'sf26',version:1,modelVersion:SF26_MODEL_VERSION,name,setup:validateSF26Setup(setup)},url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='sf26-setup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setMessage(String(e));}};
 const station=lap?sampleLap(lap,time).station:0,stale=!!lap&&JSON.stringify(lap.setup)!==JSON.stringify(setup);
 return <section className="sf26-simulation"><div className="result-provenance"><strong>SF-26 Experimental — simplified, uncalibrated engineering model</strong><span>Combustion-only · fixed aero · no electrical deployment/harvesting · no active-wing transitions · no derived suspension animation.</span><span>ESTIMATED hypotheses, not measured Ferrari performance. {SF26_MODEL_VERSION}. Changes require a new run.</span></div>
 <div className="sf26-sim-layout"><aside className="inspector"><h2>Experimental setup</h2><label>Experiment name<input value={name} maxLength={60} onChange={e=>setName(e.target.value)}/></label><p className="small-copy">All defaults are ESTIMATED; edits are USER-DEFINED. Car + driver mass excludes fuel. Component metadata never adds mass. Increased downforce area also adds estimated induced drag.</p><div className="sf26-parameters">{SF26_PARAMETERS.map(p=><label key={p.key}>{p.label}<span><input type="number" aria-label={p.label} min={p.min} max={p.max} step={p.step} value={setup[p.key] as number} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))setSetup({...setup,[p.key]:e.target.valueAsNumber});}}/> {p.unit}</span></label>)}</div><p className="small-copy">Fixed estimates: wheelbase 3.35 m; front/rear track 1.58/1.53 m; rolling radius 0.355 m; front mass 46%; CG 0.30 m; illustrative engine limit 12,000 rpm. No measured torque, tire or aero maps. No shift delay or fuel burn.</p>
 <div className="run-actions"><button className="quiet" onClick={()=>{try{setReference(validateSF26Setup(setup));setMessage('Current SF-26 setup pinned as the next-run baseline.');}catch(e){setMessage(String(e));}}}>Pin setup as baseline</button><button className="quiet" onClick={saveSetup}>Save setup</button><button className="quiet" onClick={exportSetup}>Export setup JSON</button><button className="quiet" onClick={()=>file.current?.click()}>Import setup JSON</button></div><label>Saved SF-26 setups<select value="" onChange={e=>{if(e.target.value!=='')setSetup({...saved[Number(e.target.value)].setup});}}><option value="">Select…</option>{saved.map((s,i)=><option key={i} value={i}>{s.name}</option>)}</select></label>
 <input hidden type="file" accept="application/json,.json" ref={file} onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>50000)throw Error('Setup file too large.');const v=JSON.parse(await f.text());if(v.vehicleId!=='sf26'||v.version!==1||v.modelVersion!==SF26_MODEL_VERSION)throw Error('Choose a compatible SF-26 setup; other vehicle/model files cannot be applied.');setSetup(validateSF26Setup(v.setup));setMessage('SF-26 setup imported. Rerun to update results.');}catch(error){setMessage(String(error));}if(file.current)file.current.value='';}}/>
 <TrajectoryControls value={trajectory} onChange={setTrajectory} baselineMode={baselineMode} onBaseline={setBaselineMode} lap={lap} allowOptimization={false}/><button className="primary" disabled={busy} onClick={run}>{busy?'Simulating…':'Simulate SF-26'}</button></aside>
 <div><div className="sf26-track"><Viewport vehicleId="sf26" mode="track" setup={lap?.setup??setup} explode={0} selected="" hidden={new Set()} isolate={null} transparent={false} camera="chase" cameraRevision={0} onSelect={()=>{}} lap={lap} baseline={baseline} time={time} getTime={getTime} ghost={true} line={true}/></div>
 {message&&<p role="status">{message}</p>}{stale&&<p className="result-provenance">Setup edited. Displayed results still belong to “{resultB?.name}” and its saved snapshot.</p>}
 {lap&&baseline&&<><div className="run-actions"><strong>B {formatTime(lap.lapTime)} · A {formatTime(baseline.lapTime)} · Δ {(lap.lapTime-baseline.lapTime).toFixed(3)} s · {lap.topSpeed.toFixed(1)} km/h</strong><button className="primary" onClick={()=>{const next=!playing;changeClock(clock.current,performance.now(),{playing:next,...(time>=lap.lapTime?{time:0}:{})});setPlaying(next);}}>{playing?'Pause':'Play'}</button><button className="quiet" onClick={()=>{stop();seek(0);}}>Restart</button><select aria-label="Playback speed" value={rate} onChange={e=>{const r=Number(e.target.value);setRate(r);changeClock(clock.current,performance.now(),{rate:r});}}>{[.5,1,2,4].map(r=><option key={r} value={r}>{r}×</option>)}</select><input aria-label="Playback time" type="range" min={0} max={lap.lapTime} step={.01} value={time} onChange={e=>seek(Number(e.target.value))}/></div><p className="small-copy">A: {resultA?.name} · {resultA?.trajectoryName} · {resultA?.modelVersion}<br/>B: {resultB?.name} · {resultB?.trajectoryName} · {resultB?.modelVersion}. Exact setups and sampled paths are retained in JSON exports.</p><Telemetry lap={lap} baseline={baseline} distance={station} onSeek={s=>seek(stationSample(lap,s).time)}/><SectionComparison a={baseline} b={lap} onSeek={s=>seek(stationSample(lap,s).time)}/></>}
 <Experiments vehicleId="sf26" completed={completed} baselineRun={resultA} onCompare={open} busy={busy} onWarning={setMessage}/></div></div></section>;
}
