'use client';
import {useState} from 'react';
import dynamic from 'next/dynamic';
import {Box,ChevronRight,Eye,EyeOff,Layers3,Maximize2} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sidebar,SidebarProvider,SidebarContent} from '@/components/ui/sidebar';
import SF26Simulation from './SF26Simulation';
import ComponentTree from './ComponentTree';
import {SF26_CATALOG as catalog,SF26_SOURCES,SF26_SPECS} from '@/lib/sf26';
// Dedicated SF-26 simulation is hosted beside the preserved garage.
import {DEFAULT_SETUP} from '@/lib/sim/setup';
const Viewport=dynamic(()=>import('./Viewport'),{ssr:false,loading:()=> <div className="viewport-loading">Preparing SF-26 preview…</div>});
export default function SF26Garage({onReturn}:{onReturn:()=>void}){
 const [mode,setMode]=useState<'garage'|'simulation'>('garage');
 const [selected,setSelected]=useState('sf26:front-wing'),[search,setSearch]=useState(''),[hidden,setHidden]=useState<Set<string>>(new Set()),[isolate,setIsolate]=useState<string|null>(null),[explode,setExplode]=useState(0),[transparent,setTransparent]=useState(false),[camera,setCamera]=useState('perspective'),[revision,setRevision]=useState(0);
 const part=catalog.byId.get(selected)!,geometry=catalog.resolve(selected),path=catalog.path(selected);
 const pick=(id:string)=>{setSelected(id);setHidden(h=>{const next=new Set(h);for(const ancestor of catalog.path(id))next.delete(ancestor.id);return next;});if(isolate)setIsolate(id);};
 return <main className="lab"><header className="topbar"><span className="wordmark"><span className="brand-mark">A</span>APEX<span className="brand-divider"/><span className="brand-sub">FORMULA LAB</span></span><span className="season">BUILD 3B / EXPERIMENTAL</span><button className="quiet" onClick={onReturn}>Return to F2004</button></header>
 <section className="projectbar"><div><div className="breadcrumb">WORKSPACE <ChevronRight size={12}/> SF-26 <span className="version">2026</span></div><h1>Ferrari SF-26 engineering laboratory.</h1></div><div className="project-actions"><button className="primary" onClick={()=>setMode(mode==='garage'?'simulation':'garage')}>{mode==='garage'?'Open experimental simulation':'Return to component garage'}</button></div></section>
 <div className="context-bar"><label className="car-select"><Box size={16}/><select aria-label="Vehicle" value="sf26" onChange={()=>onReturn()}><option value="f2004">Ferrari F2004 — existing simulation</option><option value="sf26">Ferrari SF-26 — experimental</option></select></label><span>Launch reference · 23 January 2026</span></div>
 <div className="result-provenance"><strong>GARAGE PREVIEW · ESTIMATED GEOMETRY</strong><span>Your F2004 setup, laps and comparison remain preserved. The dedicated experimental model uses its own assumptions; hybrid, active-aero transitions and suspension dynamics remain unsupported.</span><span>Original procedural reconstruction, not Ferrari CAD. No later race upgrades represented.</span></div>
 {mode==='garage'&&<><div className="garage-layout"><SidebarProvider className="component-sidebar-wrap"><Sidebar collapsible="none" className="component-sidebar"><SidebarContent><ComponentTree catalog={catalog} selected={selected} hidden={hidden} search={search} onSearch={setSearch} onSelect={pick}/></SidebarContent></Sidebar></SidebarProvider>
 <section className="garage-stage"><div className="stage-meta"><div><span className="eyebrow">COMPONENT LABORATORY</span><h2>SF-26 <span>/ 02</span></h2></div><span className="badge">ESTIMATED EXTERIOR</span></div>
 <Viewport vehicleId="sf26" mode="garage" setup={DEFAULT_SETUP} explode={explode} selected={selected} hidden={hidden} isolate={isolate} transparent={transparent} camera={camera} cameraRevision={revision} onSelect={pick} lap={null} baseline={null} time={0} getTime={()=>0} ghost={false} line={false}/>
 <div className="camera-tools">{['perspective','front','rear','side','top','focus'].map(k=><button key={k} disabled={k==='focus'&&!geometry.length} className={camera===k?'active':''} onClick={()=>{setCamera(k);setRevision(r=>r+1);}}>{k}</button>)}</div><div className="orbit-hint">Drag to orbit · Scroll to zoom · Right-drag to pan</div>
 <div className="explode-panel"><div><Layers3 size={16}/><span>Exploded view</span><strong>{Math.round(explode*100)}%</strong></div><Slider aria-label="SF-26 exploded view" min={0} max={1} step={.01} value={[explode]} onValueChange={v=>setExplode(v[0])}/><div className="explode-extents"><span>Assembled</span><span>Separated</span></div></div>
 <div className="stage-status"><span>{catalog.summary.geometryBacked} selectable geometry groups</span><button onClick={()=>{setHidden(new Set());setIsolate(null);setTransparent(false);}}>Show all</button></div></section>
 <aside className="inspector"><div className="panel-heading">SF-26 INSPECTOR</div><div className="component-breadcrumb">{path.map(p=><button className="quiet" key={p.id} onClick={()=>pick(p.id)}>{p.name}</button>)}</div><div className="inspector-heading"><span className="eyebrow">{part.assembly}</span><h2>{part.name}</h2><p>{part.role}</p></div>
 <div className="inspection-actions"><button disabled={!geometry.length&&!isolate} onClick={()=>setIsolate(isolate?null:selected)}><Maximize2 size={14}/>{isolate?'Exit isolate':'Isolate'}</button><button disabled={!geometry.length} onClick={()=>setHidden(h=>{const next=new Set(h);if(next.has(selected))next.delete(selected);else next.add(selected);return next;})}>{hidden.has(selected)?<Eye size={14}/>:<EyeOff size={14}/>} {hidden.has(selected)?'Show':'Hide'}</button></div>
 <label className="switch-row">X-ray view<Switch aria-label="SF-26 X-ray" checked={transparent} onCheckedChange={setTransparent}/></label>
 <div className="part-properties"><div><span>Component ID</span><code>{part.id}</code></div><div><span>Representation</span><strong>{geometry.length?`${geometry.length} geometry group(s)`:'Hierarchy only · no geometry'}</strong></div><div><span>Simulation</span><strong>{part.simulationStatus}</strong></div><div><span>Provenance</span><strong>{part.dataClass} · {part.confidence}</strong></div><div><span>Mass / material</span><strong>Unknown</strong></div><p>{part.notes}</p>{!geometry.length&&<p>No mesh is available for this internal assembly. Geometry actions are disabled; select its parent using the breadcrumb.</p>}</div>
 <div className="empty"><strong>Shared model, not independent part physics</strong><p>Combustion-only power, eight-speed gearing, axle tire forces, fixed aero and brakes are modeled. Energy management, active-wing motion and suspension dynamics remain unsupported.</p></div></aside></div>
 <section className="sf26-research"><h2>Specifications & uncertainty</h2><p>Regulatory requirements and reconstruction dimensions are kept separate. Unknown measurements remain unknown. Sources checked 18 September 2026.</p><div className="sf26-spec-scroll"><table><thead><tr><th>Specification</th><th>Value</th><th>Scope / confidence</th><th>Evidence & limitation</th></tr></thead><tbody>{SF26_SPECS.map(s=><tr key={s.name}><th>{s.name}</th><td>{s.value??'Unknown'} {s.unit}</td><td>{s.provenance}<br/>{s.scope} · {s.confidence}</td><td>{s.note}<br/><a href={SF26_SOURCES[s.source].url} target="_blank" rel="noreferrer">{SF26_SOURCES[s.source].title}</a> · {SF26_SOURCES[s.source].date??'Not verified'}</td></tr>)}</tbody></table></div><p>Ferrari’s own specification page could not be read through automated access. No unverified values from that page are claimed here. Launch imagery is used only as a reference; no external imagery or model assets are redistributed.</p></section>
 </>}{mode==='simulation'&&<SF26Simulation/>}</main>;
}
