'use client';
import {useMemo,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,ReferenceLine} from 'recharts';
import {TRACK,TRACK_LENGTH} from '@/lib/sim/track';
import type {Lap} from '@/lib/sim/physics';
export const formatTime=(s:number)=>`${Math.floor(s/60)}:${(s%60).toFixed(3).padStart(6,'0')}`;
const suspensionChannels={fl:'Front left load (N)',fr:'Front right load (N)',rl:'Rear left load (N)',rr:'Rear right load (N)',frontTransfer:'Front right − left load (N)',rearTransfer:'Rear right − left load (N)',flMM:'Front left compression (mm)',frMM:'Front right compression (mm)',rlMM:'Rear left compression (mm)',rrMM:'Rear right compression (mm)',heaveMM:'Chassis compression (mm)',pitchDeg:'Chassis pitch (°)',rollDeg:'Chassis roll (°)',insideMargin:'Inside wheel load margin (N)'};
const channels={...suspensionChannels,throttle:'Throttle demand (%)',brake:'Brake demand (%)',gear:'Selected gear',rpm:'Engine RPM',ax:'Longitudinal (g)',ay:'Lateral (g)',combined:'Combined (g)',steering:'Steering magnitude (°)',frontAero:'Front aero load (N)',rearAero:'Rear aero load (N)',downforce:'Downforce (N)',drag:'Drag (N)',utilization:'Axle grip utilization (%)',offset:'Lateral offset (m)'};
type Channel=keyof typeof channels;
function value(l:Lap,i:number,c:Channel){if(c in suspensionChannels)return l.suspension?.samples[i]?.[c as keyof typeof suspensionChannels]??null;const t=l.telemetry[i];if(c==='gear')return l.gear[i];if(c==='ax')return l.ax[i]/9.81;if(c==='ay')return l.ay[i]/9.81;if(c==='combined')return Math.hypot(l.ax[i],l.ay[i])/9.81;return t[c as keyof typeof t]*(['throttle','brake','utilization'].includes(c)?100:1);}
export function Telemetry({lap,baseline,distance=0,onSeek}:{lap:Lap;baseline:Lap;distance?:number;onSeek?:(s:number)=>void}){
 const [channel,setChannel]=useState<Channel>('throttle');
 const data=useMemo(()=>{const rows=TRACK.filter((_,i)=>i%4===0).map(p=>{const i=TRACK.indexOf(p);return {distance:p.s,modified:lap.speed[i]*3.6,baseline:baseline.speed[i]*3.6,delta:lap.time[i]-baseline.time[i],a:value(lap,i,channel),b:value(baseline,i,channel)};});rows.push({distance:TRACK_LENGTH,modified:lap.speed[0]*3.6,baseline:baseline.speed[0]*3.6,delta:lap.lapTime-baseline.lapTime,a:value(lap,0,channel),b:value(baseline,0,channel)});return rows;},[lap,baseline,channel]);
 const i=Math.min(TRACK.length-1,Math.floor(distance/TRACK_LENGTH*TRACK.length)),t=lap.telemetry[i];
 return <div className="telemetry-charts"><div className="telemetry-toolbar"><label>Engineering channel <select aria-label="Telemetry channel" value={channel} onChange={e=>setChannel(e.target.value as Channel)}>{Object.entries(channels).map(([k,v])=><option key={k} value={k} disabled={k in suspensionChannels&&!lap.suspension&&!baseline.suspension}>{v}{k in suspensionChannels&&!lap.suspension&&!baseline.suspension?' — unavailable':''}</option>)}</select></label><label htmlFor="telemetry-station">Track station {distance.toFixed(0)} m</label><input id="telemetry-station" aria-label="Telemetry track station" type="range" min={0} max={TRACK_LENGTH} step={1} value={distance} onChange={e=>onSeek?.(Number(e.target.value))}/><span>Click a chart to seek playback</span></div>
 <div className="telemetry-values" aria-live="off"><span>Gear {lap.gear[i]}</span><span>{t.rpm.toFixed(0)} rpm</span><span>Throttle {(t.throttle*100).toFixed(0)}%</span><span>Brake {(t.brake*100).toFixed(0)}%</span><span>Grip {(t.utilization*100).toFixed(0)}%</span><span>Offset {t.offset.toFixed(2)} m</span></div>
 {['speed','delta','channel'].map(kind=><div className="chart" key={kind}><div className="chart-label"><span>{kind==='speed'?'SPEED / TRACK STATION':kind==='delta'?'TIME DELTA / TRACK STATION':channels[channel]}</span><span>{kind==='speed'?'km/h':kind==='delta'?'seconds · negative is faster':'estimated / derived'}</span></div><ResponsiveContainer width="100%" height={180}><LineChart data={data} syncId="telemetry" onClick={state=>{if(state?.activeLabel!==undefined)onSeek?.(Number(state.activeLabel));}} margin={{top:15,right:18,left:-12,bottom:2}}><CartesianGrid vertical={false} stroke="#2c343a"/><XAxis dataKey="distance" type="number" domain={[0,TRACK_LENGTH]} tick={{fill:'#97a3ac',fontSize:12}} tickFormatter={n=>`${(n/1000).toFixed(1)}k`} axisLine={false} tickLine={false}/><YAxis tick={{fill:'#97a3ac',fontSize:12}} axisLine={false} tickLine={false} domain={['auto','auto']} tickFormatter={n=>n.toFixed(1)}/><Tooltip contentStyle={{background:'#171f25',border:'1px solid #44505b',borderRadius:8,color:'#fff'}} labelFormatter={n=>`${Number(n).toFixed(0)} m`} formatter={v=>Number(v).toFixed(2)}/><ReferenceLine x={distance} stroke="#a5afb6" strokeDasharray="3 3"/>{kind!=='delta'?<><Line name="Baseline" type="linear" dataKey={kind==='speed'?'baseline':'b'} stroke="#85c8d0" strokeWidth={1.5} dot={false} isAnimationActive={false}/><Line name="Experiment" type="linear" dataKey={kind==='speed'?'modified':'a'} stroke="#ff754c" strokeWidth={2} dot={false} isAnimationActive={false}/></>:<><ReferenceLine y={0} stroke="#78858d"/><Line name="Delta" type="linear" dataKey="delta" stroke="#ff754c" strokeWidth={2} dot={false} isAnimationActive={false}/></>}</LineChart></ResponsiveContainer></div>)}
 {lap.vehicleId==='sf26'?<p className="small-copy">SF-26 suspension channels and attitude are unavailable. Wheel spin and steering are kinematic visualization only; no hidden F2004 suspension parameters are used.</p>:<p className="small-copy">Suspension: DERIVED / ESTIMATED quasi-static, physical 1×. Wheel loads include aero and load transfer; compression is relative to static preload, with bounded travel (not a bottoming solver). Tires follow the sampled road plane; per-wheel terrain, linkage articulation, damping and tire deformation are unsupported. These channels do not change lap times. {(!lap.suspension||!baseline.suspension)?'Some saved runs lack suspension telemetry; missing channels are unavailable, not zero.':lap.suspension.version!==baseline.suspension.version?'Suspension versions differ: derived channels may not be comparable.':`Telemetry ${lap.suspension.version}.`} {lap.suspension?.samples[i]?.warning?'Warning at cursor: wheel lift and/or estimated travel exceeded; bounded attitude is outside model validity.':''}</p>}
 <p className="small-copy">Throttle/brake are inferred demands, not driver inputs. Steering is a bicycle-model magnitude. Grip utilization uses estimated axle friction ellipses. Gray cursor and playback share track station; sectors use common reference-distance thirds.</p></div>;
}
