'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createSF26} from './sf26Car';
import {SF26_CATALOG} from '@/lib/sf26';
import {createCar} from './car';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {createCircuit} from './circuit';
import {TRACK} from '@/lib/sim/track';
import {type Lap} from '@/lib/sim/physics';
import {sampleSuspension} from '@/lib/sim/suspension';
import {sampleMotion} from '@/lib/sim/motion';
import {resolveGeometryIds as resolveLegacyGeometry} from '@/lib/components';
import type {Setup} from '@/lib/sim/setup';
type Props={vehicleId?:'f2004'|'sf26';mode:'garage'|'track';setup:Setup;explode:number;selected:string;hidden:Set<string>;isolate:string|null;transparent:boolean;camera:string;cameraRevision:number;onSelect:(s:string)=>void;lap:Lap|null;baseline:Lap|null;time:number;getTime:()=>number;ghost:boolean;line:boolean};
export default function Viewport(props:Props){const host=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;const [error,setError]=useState(''),[quality,setQuality]=useState('balanced');
 useEffect(()=>{const el=host.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch{setError('3D rendering requires WebGL. Try an updated browser with hardware acceleration. Setup editing and lap comparisons remain available.');return;}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,quality==='high'?2:1.25));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor(0x14191d);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label',props.mode==='garage'?'Interactive 3D car; use component list for keyboard selection':'3D simulation track');
 const scene=new THREE.Scene();const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;scene.environmentIntensity=props.mode==='garage'?.65:.35;room.dispose();pmrem.dispose();scene.fog=new THREE.Fog(0x14191d,props.mode==='garage'?18:1900,props.mode==='garage'?45:5000);
 const cam=new THREE.PerspectiveCamera(38,1,props.mode==='garage'?.005:.05,props.mode==='garage'?100:10000),controls=new OrbitControls(cam,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.49;controls.minDistance=props.mode==='garage'?.18:12;controls.maxDistance=props.mode==='garage'?22:4000;
 scene.add(new THREE.HemisphereLight(0xe5f4ff,0x32383f,.9));const key=new THREE.DirectionalLight(0xffffff,2.7);key.position.set(3,8,-4);key.castShadow=true;key.shadow.mapSize.set(quality==='high'?2048:1024,quality==='high'?2048:1024);key.shadow.camera.left=-5;key.shadow.camera.right=5;key.shadow.camera.top=5;key.shadow.camera.bottom=-5;key.shadow.bias=-.001;scene.add(key);const rim=new THREE.DirectionalLight(0xc6d8ee,.8);rim.position.set(-5,2,4);scene.add(rim);
 if(props.mode==='track'){scene.background=new THREE.Color(0xa0b4bf);scene.fog=new THREE.Fog(0xa0b4bf,1800,5000);key.position.set(100,180,-80);key.shadow.camera.left=-25;key.shadow.camera.right=25;key.shadow.camera.top=25;key.shadow.camera.bottom=-25;scene.add(key.target);}
 const resolveGeometryIds=props.vehicleId==='sf26'?SF26_CATALOG.resolve:resolveLegacyGeometry;
 const car=props.vehicleId==='sf26'?createSF26():createCar();scene.add(car.group);const ghostCar=props.vehicleId==='sf26'?createSF26(true):createCar(true);scene.add(ghostCar.group);ghostCar.group.visible=false;
 const stage=new THREE.Mesh(new THREE.CylinderGeometry(3.75,3.85,.11,96),new THREE.MeshStandardMaterial({color:0x22292e,roughness:.66,metalness:.25}));stage.position.y=-.065;stage.receiveShadow=true;
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(props.mode==='garage'?200:8000,props.mode==='garage'?200:8000),new THREE.MeshStandardMaterial({color:props.mode==='garage'?0x14191d:0x526549,roughness:.95}));floor.rotation.x=-Math.PI/2;floor.position.y=-.13;floor.receiveShadow=true;scene.add(floor);
 let racingLine:THREE.Line|undefined,baselineLine:THREE.Line|undefined,centerLine:THREE.Line|undefined;
 if(props.mode==='garage'){
 scene.add(stage);const circle=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(Array.from({length:128},(_,i)=>new THREE.Vector3(Math.sin(i/128*Math.PI*2)*3.72,.003,Math.cos(i/128*Math.PI*2)*3.72))),new THREE.LineBasicMaterial({color:0x49535b}));scene.add(circle);
 const grid=new THREE.GridHelper(200,100,0x283139,0x20282e);grid.position.y=-.12;scene.add(grid);
 }else{
 const circuit=createCircuit();scene.add(circuit.group);racingLine=circuit.line;(racingLine.material as THREE.LineBasicMaterial).color.set('#ff754c');
 baselineLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:'#85c8d0'}));scene.add(baselineLine);
 const pts=TRACK.map(p=>new THREE.Vector3(p.x,p.y+.04,p.z));pts.push(pts[0]);
 centerLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:'#879397',transparent:true,opacity:.6}));scene.add(centerLine);
 }
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let hover='',down=[0,0],active=true,frame=0,last=performance.now(),revision=-1,lastCamera='',focusPart='',renderedLap:Lap|null=null;
 const hit=(e:PointerEvent)=>{const r=el.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,cam);return ray.intersectObjects(car.group.children,true).find(h=>{let o:THREE.Object3D|null=h.object;while(o){if(!o.visible)return false;o=o.parent;}return true;})?.object.userData.partId||'';};
 const move=(e:PointerEvent)=>{if(latest.current.mode==='garage'){hover=hit(e);el.style.cursor=hover?'pointer':'grab';}};
 const startDrag=(e:PointerEvent)=>{down=[e.clientX,e.clientY];};const click=(e:PointerEvent)=>{if(latest.current.mode==='garage'&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<4){const id=hit(e);if(id)latest.current.onSelect(id);}};
 el.addEventListener('pointermove',move);el.addEventListener('pointerdown',startDrag);el.addEventListener('pointerup',click);
 const lost=(e:Event)=>{e.preventDefault();setError('The 3D graphics context was lost. Reload this page to restore it; saved configurations are kept.');};renderer.domElement.addEventListener('webglcontextlost',lost);
 const resize=new ResizeObserver(()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);cam.aspect=w/Math.max(h,1);cam.updateProjectionMatrix();});resize.observe(el);
 const animate=()=>{if(!active)return;const now=performance.now(),dt=Math.min(.1,(now-last)/1000);last=now;const p=latest.current;
 const selectedGeometry=new Set(resolveGeometryIds(p.selected)),hiddenGeometry=new Set([...p.hidden].flatMap(resolveGeometryIds)),isolateGeometry=p.isolate?new Set(resolveGeometryIds(p.isolate)):null;
 if(p.cameraRevision!==revision||p.camera!==lastCamera||(p.camera==='focus'&&focusPart!==p.selected)){revision=p.cameraRevision;lastCamera=p.camera;focusPart=p.selected;if(p.mode==='garage'){const positions:Record<string,number[]>={perspective:[6,3.3,-7],side:[7,1.6,0],rear:[0,1.4,7],front:[0,1.4,-8],top:[.01,9,0]};cam.position.set(...(positions[p.camera]??positions.perspective) as [number,number,number]);controls.target.set(0,.35,0);if(p.camera==='focus'&&selectedGeometry.size){car.group.updateMatrixWorld(true);const box=new THREE.Box3();for(const id of selectedGeometry){const object=car.parts.get(id);if(object)box.expandByObject(object);}const center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length();controls.target.copy(center);cam.position.copy(center).add(new THREE.Vector3(1,.55,-1).normalize().multiplyScalar(Math.max(.35,size*1.8)));}}else{cam.position.set(900,1850,1350);controls.target.set(0,0,0);}controls.update();}
 car.update(p.setup,p.mode==='garage'?p.explode:0,p.mode==='garage'?selectedGeometry:new Set<string>(),hover,p.mode==='garage'?hiddenGeometry:new Set(),p.mode==='garage'?isolateGeometry:null,p.mode==='garage'?p.transparent:false,dt);
 if(p.mode==='track'&&p.lap){if(renderedLap!==p.lap&&racingLine){renderedLap=p.lap;const points=p.lap.path.map(q=>new THREE.Vector3(q.x,q.y+.06,q.z));points.push(points[0]);racingLine.geometry.dispose();racingLine.geometry=new THREE.BufferGeometry().setFromPoints(points);if(baselineLine&&p.baseline){const bp=p.baseline.path.map(q=>new THREE.Vector3(q.x,q.y+.08,q.z));bp.push(bp[0]);baselineLine.geometry.dispose();baselineLine.geometry=new THREE.BufferGeometry().setFromPoints(bp);}}const playbackTime=p.getTime(),s=sampleMotion(p.lap,playbackTime);car.drive(s.s,s.steer);car.attitude(sampleSuspension(p.lap,s.i,s.u));car.group.position.set(s.x,s.y,s.z);car.group.rotation.set(s.pitch,s.heading+Math.PI,0,'YXZ');key.position.set(s.x+50,s.y+100,s.z-40);key.target.position.copy(car.group.position);ghostCar.group.visible=p.ghost&&!!p.baseline;if(p.baseline){const b=sampleMotion(p.baseline,Math.min(playbackTime,p.baseline.lapTime));ghostCar.group.position.set(b.x,b.y+.002,b.z);ghostCar.group.rotation.set(b.pitch,b.heading+Math.PI,0,'YXZ');ghostCar.update(p.baseline.setup,0,'','',new Set(),null,false,dt);ghostCar.drive(b.s,b.steer);ghostCar.attitude(sampleSuspension(p.baseline,b.i,b.u));}
 controls.enabled=p.camera==='overhead';if(p.camera!=='overhead'){const dir=new THREE.Vector3(Math.sin(s.heading)*Math.cos(s.pitch),Math.sin(s.pitch),Math.cos(s.heading)*Math.cos(s.pitch)),base=new THREE.Vector3(s.x,s.y,s.z);const onboard=p.camera==='onboard';cam.position.copy(base).addScaledVector(dir,onboard?-.15:-12).add(new THREE.Vector3(0,onboard?.74:3.7,0));if(p.camera==='trackside'){const q=p.lap.path[(s.i+35)%p.lap.path.length],r=p.lap.path[(s.i+36)%p.lap.path.length];cam.position.set(q.x+(r.x-q.x)*s.u+Math.cos(s.heading)*24,q.y+(r.y-q.y)*s.u+3,q.z+(r.z-q.z)*s.u-Math.sin(s.heading)*24);cam.lookAt(base); }else cam.lookAt(base.clone().addScaledVector(dir,onboard?35:12).add(new THREE.Vector3(0,.7,0)));}else controls.update();
 if(racingLine)racingLine.visible=p.line;if(baselineLine)baselineLine.visible=p.line;if(centerLine)centerLine.visible=p.line;
 }else controls.update();renderer.render(scene,cam);frame=requestAnimationFrame(animate);};animate();
 return()=>{active=false;cancelAnimationFrame(frame);resize.disconnect();controls.dispose();el.removeEventListener('pointermove',move);el.removeEventListener('pointerdown',startDrag);el.removeEventListener('pointerup',click);scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line){o.geometry.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>{for(const v of Object.values(m))if(v instanceof THREE.Texture)v.dispose();m.dispose();});}});environment.dispose();renderer.dispose();renderer.domElement.remove();};
 },[props.mode,props.vehicleId,quality]);
 return <div className="viewport-canvas" ref={host}><label className="graphics-quality">Graphics <select aria-label="Graphics quality" value={quality} onChange={e=>setQuality(e.target.value)}><option value="balanced">Balanced</option><option value="high">High</option></select></label>{error&&<div className="viewport-error" role="alert">{error}</div>}</div>;
}
